name: Docker Image CI

on:
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.HUB_KRIUSE }}
      - name: Build the Docker image
        run: |
          docker buildx create --use --platform=linux/amd64,linux/arm64,linux/ppc64le --name multi-platform-builder
          docker buildx ls
          IMG=openkruise/kruise-manager:${{ github.ref_name }} make docker-multiarch
